FIELD_TYPES = {
    "general": 0,
    "optional": 1,
    "amount": 2,
    "date": 3
}

# FIELDS = dict()
# FIELDS["Admit Date"] = FIELD_TYPES["general"]
# FIELDS["Admit Time"] = FIELD_TYPES["general"]
# FIELDS["Room"] = FIELD_TYPES["general"]
# FIELDS["MPI"] = FIELD_TYPES["general"]
# FIELDS["Case #"] = FIELD_TYPES["general"]
# FIELDS["Pt TYPE"] = FIELD_TYPES["general"]
# FIELDS["F/C"] = FIELD_TYPES["general"]
# FIELDS["M/S"] = FIELD_TYPES["general"]
# FIELDS["Birthdate"] = FIELD_TYPES["general"]
# FIELDS["Religion"] = FIELD_TYPES["general"]
# FIELDS["Race"] = FIELD_TYPES["general"]
# FIELDS["Patient name and Address"] = FIELD_TYPES["general"]
# FIELDS["SSN"] = FIELD_TYPES["general"]
# FIELDS["Employment Information"] = FIELD_TYPES["general"]
# FIELDS["Phone"] = FIELD_TYPES["general"]
# FIELDS["Relationship to Patient"] = FIELD_TYPES["general"]
# FIELDS["Guarantor Name and Address"] = FIELD_TYPES["general"]
# FIELDS["Insurance Plan 1"] = FIELD_TYPES["general"]
# FIELDS["Group Number"] = FIELD_TYPES["general"]
# FIELDS["Policy Number"] = FIELD_TYPES["general"]
# FIELDS["Insurance Plan 2"] = FIELD_TYPES["general"]
# FIELDS["Type"] = FIELD_TYPES["general"]
# FIELDS["Physician Name"] = FIELD_TYPES["general"]
# FIELDS["Address"] = FIELD_TYPES["general"]
# FIELDS["City/State/Zip"] = FIELD_TYPES["general"]
# FIELDS["Code Numbers"] = FIELD_TYPES["general"]
# FIELDS["Principal and Secondary Diagnoses"] = FIELD_TYPES["general"]
#
# FIELDS["Operation"] = FIELD_TYPES["general"]
# FIELDS["Surgeon"] = FIELD_TYPES["general"]
# FIELDS["Consultant"] = FIELD_TYPES["general"]
# FIELDS["Anaesthetist"] = FIELD_TYPES["general"]
# FIELDS["Location"] = FIELD_TYPES["general"]
# FIELDS["Sedation"] = FIELD_TYPES["general"]
# FIELDS["Age"] = FIELD_TYPES["general"]
# FIELDS["GP"] = FIELD_TYPES["general"]
#
# FIELDS["NHS No."] = FIELD_TYPES["general"]
# FIELDS["Hospital No."] = FIELD_TYPES["general"]
# FIELDS["Tel (eve)"] = FIELD_TYPES["general"]
# FIELDS["Eye"] = FIELD_TYPES["general"]
# FIELDS["Indication for surgery"] = FIELD_TYPES["general"]
# FIELDS["Procedure"] = FIELD_TYPES["general"]
# FIELDS["Preparation"] = FIELD_TYPES["general"]
# FIELDS["Viscoelastic"] = FIELD_TYPES["general"]
# FIELDS["Capsulotomy"] = FIELD_TYPES["general"]
#
# FIELDS["Pred.post-op refn"] = FIELD_TYPES["general"]
# FIELDS["Wound closure"] = FIELD_TYPES["general"]
# FIELDS["Antibiotic"] = FIELD_TYPES["general"]
# FIELDS["Additives in BSS"] = FIELD_TYPES["general"]
# FIELDS["Complications"] = FIELD_TYPES["general"]
# FIELDS["Other surgical details"] = FIELD_TYPES["general"]
# FIELDS["Pupil Size"] = FIELD_TYPES["general"]
#
# FIELDS["Surname"] = FIELD_TYPES["general"]
# FIELDS["PAT NO"] = FIELD_TYPES["general"]
# FIELDS["NHS No"] = FIELD_TYPES["general"]
# FIELDS["Ward"] = FIELD_TYPES["general"]
# FIELDS["SA (m2)"] = FIELD_TYPES["general"]
# FIELDS["Height (m)"] = FIELD_TYPES["general"]
# FIELDS["Allocated by"] = FIELD_TYPES["general"]
# FIELDS["Date"] = FIELD_TYPES["general"]
# FIELDS["Confirmed by"] = FIELD_TYPES["general"]
# FIELDS["Checked by"] = FIELD_TYPES["general"]
#
#
# FIELDS["Height"] = FIELD_TYPES["general"]
# FIELDS["Weight"] = FIELD_TYPES["general"]
# FIELDS["SA"] = FIELD_TYPES["general"]
# FIELDS["BILIRUBIN 3 DAYS"] = FIELD_TYPES["general"]
# FIELDS["GFR"] = FIELD_TYPES["general"]
# FIELDS["Hepatitis screen"] = FIELD_TYPES["general"]
# FIELDS["Irradiated blood products req"] = FIELD_TYPES["general"]
# FIELDS["NEUTROPHILS"] = FIELD_TYPES["general"]
# FIELDS["PLATELETS"] = FIELD_TYPES["general"]
# FIELDS["market value"] = FIELD_TYPES["general"]
#
# FIELDS["Issued"] = FIELD_TYPES["general"]
# FIELDS["Expires"] = FIELD_TYPES["general"]
# FIELDS["Class"] = FIELD_TYPES["general"]
# FIELDS["DOB"] = FIELD_TYPES["general"]
# FIELDS["DL"] = FIELD_TYPES["general"]
# FIELDS["Endoresments"] = FIELD_TYPES["general"]
# FIELDS["Wt"] = FIELD_TYPES["general"]
# FIELDS["Ht"] = FIELD_TYPES["general"]
# FIELDS["Sex"] = FIELD_TYPES["general"]
# FIELDS["Eyes"] = FIELD_TYPES["general"]
# FIELDS["Hair"] = FIELD_TYPES["general"]
#
#
# FIELDS["VEHICLE MAKE"] = FIELD_TYPES["general"]
# FIELDS["MODEL"] = FIELD_TYPES["general"]
# FIELDS["VEHICLE STYLE"] = FIELD_TYPES["general"]
# FIELDS["VEHICLE IDENTIFICATION NUMBER"] = FIELD_TYPES["general"]
# FIELDS["VEHICLE STATUS"] = FIELD_TYPES["general"]
# FIELDS["BODY COLOR"] = FIELD_TYPES["general"]
# FIELDS["CODE"] = FIELD_TYPES["general"]
# FIELDS["FUEL"] = FIELD_TYPES["general"]
# FIELDS["LICENCE PLATE NO"] = FIELD_TYPES["general"]
# FIELDS["CLASS"] = FIELD_TYPES["general"]
# FIELDS["LICENCED MASS"] = FIELD_TYPES["general"]
# FIELDS["EXPIRY DATE"] = FIELD_TYPES["general"]
# FIELDS["REGISTRY AGENT"] = FIELD_TYPES["general"]
# FIELDS["VALIDATED"] = FIELD_TYPES["general"]
# FIELDS["MAXIMUM SERVICE AMOUNT"] = FIELD_TYPES["general"]
# FIELDS["ISSUED"] = FIELD_TYPES["general"]
#
# FIELDS["Date"] = FIELD_TYPES["general"]
# FIELDS["Postal Code"] = FIELD_TYPES["general"]
# FIELDS["Province"] = FIELD_TYPES["general"]
# FIELDS["Branch Address"] = FIELD_TYPES["general"]
# FIELDS["City"] = FIELD_TYPES["general"]
#
#
# FIELDS["Dat"] = FIELD_TYPES["general"]
# FIELDS["Automobile"] = FIELD_TYPES["general"]
# FIELDS["Serial Number"] = FIELD_TYPES["general"]
# FIELDS["Type of Coverage"] = FIELD_TYPES["general"]
# FIELDS["Collision"] = FIELD_TYPES["general"]
# FIELDS["Comprehensive"] = FIELD_TYPES["general"]
# FIELDS["Third Party Liability"] = FIELD_TYPES["general"]
# FIELDS["Effective Date"] = FIELD_TYPES["general"]
# FIELDS["Expiry Date"] = FIELD_TYPES["general"]
# FIELDS["Conditions"] = FIELD_TYPES["general"]
#
# FIELDS["Vehicle Service Contract Number"] = FIELD_TYPES["general"]
# FIELDS["DEALERSHIP NAME"] = FIELD_TYPES["general"]
# FIELDS["ASSURANT DEALER CODE"] = FIELD_TYPES["general"]
# FIELDS["ADDRESS"] = FIELD_TYPES["general"]
# FIELDS["PHONE NUMBER"] = FIELD_TYPES["general"]
# FIELDS["NAME OF LIENHOLDER"] = FIELD_TYPES["general"]
# FIELDS["YEAR"] = FIELD_TYPES["general"]
# FIELDS["SERIAL NUMBER"] = FIELD_TYPES["general"]
# FIELDS["ENGINE SIZE"] = FIELD_TYPES["general"]
# FIELDS["ODOMETER READING"] = FIELD_TYPES["general"]
# FIELDS["VEHICLE PURCHASE PRICE"] = FIELD_TYPES["general"]
# FIELDS["PLAN"] = FIELD_TYPES["general"]
# FIELDS["VSC PURCHASE DATE"] = FIELD_TYPES["general"]
# FIELDS["END OF COVERAGE"] = FIELD_TYPES["general"]
#
#
#
# FIELDS["Loan Agreement Number"] = FIELD_TYPES["general"]
# FIELDS["SECTION 1"] = FIELD_TYPES["general"]
# FIELDS["SECTION 2"] = FIELD_TYPES["general"]
# FIELDS["VIN#"] = FIELD_TYPES["general"]
# FIELDS["Year"] = FIELD_TYPES["general"]
# FIELDS["Make"] = FIELD_TYPES["general"]
# FIELDS["Model"] = FIELD_TYPES["general"]
# FIELDS["Province of Registration"] = FIELD_TYPES["general"]
# FIELDS["SECTION 3"] = FIELD_TYPES["general"]
# FIELDS["EFFECTIVE DATE"] = FIELD_TYPES["general"]
# FIELDS["Total of Invoices"] = FIELD_TYPES["general"]
# FIELDS["PPSA Costs"] = FIELD_TYPES["general"]
# FIELDS["Other Services"] = FIELD_TYPES["general"]
# FIELDS["Total of Advances"] = FIELD_TYPES["general"]
# FIELDS["Loan Fee"] = FIELD_TYPES["general"]
# FIELDS["Amount to be Financed"] = FIELD_TYPES["general"]
# FIELDS["END OF COVERAGE"] = FIELD_TYPES["general"]
#
# FIELDS["Modum Job #"] = FIELD_TYPES["general"]
# FIELDS["Client"] = FIELD_TYPES["general"]
# FIELDS["Sales Comparison Approach"] = FIELD_TYPES["general"]
# FIELDS["Exposure Time"] = FIELD_TYPES["general"]
# FIELDS["Date of Report"] = FIELD_TYPES["general"]
# FIELDS["Gross Land Area"] = FIELD_TYPES["general"]
# FIELDS["Property Type"] = FIELD_TYPES["general"]
# FIELDS["GBA"] = FIELD_TYPES["general"]
# FIELDS["NRA"] = FIELD_TYPES["general"]
# FIELDS["Occupancy Type"] = FIELD_TYPES["general"]
# FIELDS["Year Built"] = FIELD_TYPES["general"]
# FIELDS["Property Condition"] = FIELD_TYPES["general"]
# FIELDS["Market Value"] = FIELD_TYPES["general"]
#
#
# FIELDS["Address"] = FIELD_TYPES["general"]
# FIELDS["City, State Zip"] = FIELD_TYPES["general"]
# FIELDS["Proximity To Subject"] = FIELD_TYPES["general"]
# FIELDS["Property Type"] = FIELD_TYPES["general"]
# FIELDS["Year Built"] = FIELD_TYPES["general"]
# FIELDS["Gross Building Area (GBA)"] = FIELD_TYPES["general"]
# FIELDS["Net Rentable Area (NRA)"] = FIELD_TYPES["general"]
# FIELDS["Land Size"] = FIELD_TYPES["general"]
# FIELDS["Land To Building Ratio"] = FIELD_TYPES["general"]
# FIELDS["Sales Date"] = FIELD_TYPES["general"]
# FIELDS["Sales Price"] = FIELD_TYPES["general"]
#
# FIELDS["Employee ID"] = FIELD_TYPES["general"]
# FIELDS["Joining Date"] = FIELD_TYPES["general"]
# FIELDS["Blood Group"] = FIELD_TYPES["general"]
#
# FIELDS["CELL"] = FIELD_TYPES["general"]
# FIELDS["Mail"] = FIELD_TYPES["general"]
# FIELDS["PHONE"] = FIELD_TYPES["general"]
# FIELDS["Property Location"] = FIELD_TYPES["general"]
# FIELDS["Sale Date"] = FIELD_TYPES["general"]
# FIELDS["Sale Price"] = FIELD_TYPES["general"]
# FIELDS["Recording"] = FIELD_TYPES["general"]
# FIELDS["Joining Date"] = FIELD_TYPES["general"]
# FIELDS["Parcel I.D."] = FIELD_TYPES["general"]
# FIELDS["Grantor"] = FIELD_TYPES["general"]
# FIELDS["Grantee"] = FIELD_TYPES["general"]
# FIELDS["Site Size - Acres"] = FIELD_TYPES["general"]
# FIELDS["Sq. Ft."] = FIELD_TYPES["general"]
# FIELDS["Price Per Acre"] = FIELD_TYPES["general"]
# FIELDS["Price Per Square Foot"] = FIELD_TYPES["general"]
# FIELDS["Rights Conveyed"] = FIELD_TYPES["general"]
# FIELDS["Relationship of Parties"] = FIELD_TYPES["general"]
# FIELDS["Jurisdiction"] = FIELD_TYPES["general"]
# FIELDS["Finished Product Type"] = FIELD_TYPES["general"]
# FIELDS["Confirmation"] = FIELD_TYPES["general"]
#
# FIELDS["Market Value Conclusions"] = FIELD_TYPES["general"]
#
#
